<%@ page import="ASDB.C_AS_Select" %>
<%@ page import="java.util.ArrayList" %>
<%@ page import="java.sql.SQLException" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<script src="/js/jquery-2.2.0.min.js" type="text/javascript"></script>
<script src="/js/bootbox.min.js" type="text/javascript"></script>
<script src="/js/stupidtable.min.js" type="text/javascript"></script>

<%System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646");%>


<%
    /**
     * used to display list of performance indicator/outcome links page.
     */


    String id = "";
    String Termid = "";
    if(request.getParameter("cycle") != null && request.getParameter("term") != null){
        id  = request.getParameter("cycle");
        Termid  = request.getParameter("term");
    }

%>
<%System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646");%>

<%
    String ulogo = (String) config.getServletContext().getAttribute("ulogo");
    String uname = (String) config.getServletContext().getAttribute("uname");
    String cname = (String) config.getServletContext().getAttribute("cname");

    if(ulogo!= null){
        out.println("<div id=\"print-note\" class=\" centerI\" > \n" +
                "                            <img width=\"135px\" class=\"\" " +
                "src=\""+ulogo+"\" alt=\""+uname+"\"></div>");
    }
%>
<%System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646    3");%>

<h6 id="print-note">This ducument was generated by ABETAS for <%=cname%>, <%=uname%></h6>

        <div class="container">

            <div class="row">
                <div class="col-md-7 col-md-offset-2">
                    <nav>
                        <ol class="cd-breadcrumb triangle small">
                            <li ><em>Courses</em></li>
                            <li class="current"><em>Link PI/Outcomes</em></li>
                        </ol>
                    </nav>
                </div>
            </div>

            <!--  Here is row -->
            <div class="row">

                <h2 class="text-center">Link Performance Indicator with Student Outcomes</h2>
                <legend></legend>
                <div class="col-md-12 ">
                    <p class="notPrintable">Click "Add" to enter a new performance indicator and students outcome link for <% if(request.getParameter("programID")!=null) {
                        C_AS_Select ssselect = new C_AS_Select();
                        try {
                            String rs = ssselect.selectProgramName(Integer.parseInt(request.getParameter("programID")));
                            out.print(rs);
                        } catch (ClassNotFoundException e) {
                            e.printStackTrace();
                        } catch (SQLException e) {
                            e.printStackTrace();
                        }
                    }
                    %> program</p>
                    <div id="print" class="input-group notPrintable"> <span class="input-group-addon">Filter</span>

                        <input id="filter" type="text" class="form-control" placeholder=" by students outcome, performance indicator, course code or type  ">
                    </div>
                        <!-- Table -->
                        <table class="table table-hover table-striped table-bordered text-center" id="sTable">
                            <thead>

                            <tr>
                                <th data-sort="string-ins">Students Outcome</th>
                                <th data-sort="string-ins">Performance Indicator</th>
                                <th data-sort="string-ins">Course</th>
                                <th data-sort="string">Type</th>
                                <th data-sort="int">Threshold</th>
                                <th class="notPrintable">Edit</th>
                                <th class="notPrintable">Delete</th>
                            </tr>
                            </thead>
                            <%System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646       4");%>

                            <tbody class="searchable">
                                <%

                                    C_AS_Select aselect = new C_AS_Select();
                                System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646     5");

                                    try {
                                        ArrayList<ArrayList<String>> rs = aselect.selectPILinks(Integer.parseInt(Termid),Integer.parseInt(request.getParameter("programID")));
                                        ArrayList<String> rsRow ;
                                        System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646     6");
                                        int threshold = -1;

                                        for (int i=0; i<rs.size();i++){
                                            rsRow = new ArrayList<String>();
                                            rsRow = rs.get(i);
                                            threshold = aselect.selectThreshold(Integer.parseInt(rsRow.get(2).substring(0, rsRow.get(1).indexOf(':'))));
                                            out.print("<tr>");
                                            for (int j=1; j<rsRow.size();j++) {
                                                System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646  7");
                                                if(j==1||j==2||j==3||j==4){
                                                    out.print("<td>");
                                                    System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646  inn if 1 +  "+ rsRow.get(j).length());

                                                    if(rsRow.get(j).length()> 70){
                                                        System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646 inn if 2");
                                                        out.print(rsRow.get(j).substring(0,70)+"...");
                                                        System.out.println("real   "+rsRow.get(j).substring(0,70)+"...");
                                                    }else {
                                                        System.out.println("real  in else "+rsRow.get(j));

                                                        out.print(rsRow.get(j));

                                                        System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646   inn  esle");
                                                    }
                                                    out.print("</td>");
                                                }
                                                System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646  8");
                                            }
                                System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646       innn");

                                out.print("<td>");
                                            out.print(threshold);
                                            out.print("</td>");
                                            out.print("<td class=\"notPrintable\">" +
                                                    "                            <form method=\"post\" action=\"index.jsp\">\n" +
                                                    "                            <input name=\"page\" value=\"updatePILink\" hidden />\n" +
                                                    "                            <input name=\"cycle\" value=\""+id+"\" hidden />\n" +
                                                    "                            <input name=\"term\" value=\""+Termid+"\" hidden />\n" +
                                                    "                            <input name=\"LinkID\" value=\""+rsRow.get(0)+"\" hidden />\n" +
                                                    "                            <input name=\"OutValue\" value=\""+rsRow.get(1).substring(0, rsRow.get(1).indexOf(':'))+"\" hidden />\n" +
                                                    "                            <input name=\"PIValue\" value=\""+rsRow.get(2)+"\" hidden />\n" +
                                                    "                            <input name=\"CourseValue\" value=\""+rsRow.get(3)+"\" hidden />\n" +
                                                    "                            <input name=\"TypeValue\" value=\""+rsRow.get(4)+"\" hidden />\n" +
                                                    "                            <input name=\"PValue\" value=\""+rsRow.get(6)+"\" hidden />\n" +
                                                    "                            <input name=\"RubricValue\" value=\""+rsRow.get(5)+"\" hidden />\n" +
                                                    "                            <input name=\"TermValue\" value=\""+rsRow.get(7)+"\" hidden />\n" +
                                                    "                            <input name=\"programID\" value=\""+request.getParameter("programID")+"\" hidden />\n" +
                                                    "                            <button  type=\"submit\" title=\"Edit\" class=\"btn btn-link btn-Y \"><i class=\"fui-new icon30\"></i></button>\n" +
                                                    "                               </td>" +
                                                    "                            </form>" +
                                                    "                            <form method=\"post\" class=\"delForm\" action=\"/DeletePILinks\">\n" +
                                                    "                            <input name=\"page\" id=\"page\" value=\"delete\" hidden />\n" +
                                                    "                            <input name=\"cycle\" value=\""+id+"\" hidden />\n" +
                                                    "                            <input name=\"term\" value=\""+Termid+"\" hidden />\n" +
                                                    "                            <input name=\"LinkID\" value=\""+rsRow.get(0)+"\" hidden />\n" +
                                                    "                            <input name=\"RubricValue\" value=\""+rsRow.get(5)+"\" hidden />\n" +
                                                    "                            <input name=\"programID\" value=\""+request.getParameter("programID")+"\" hidden />\n" +
                                                    "                               <td class=\"notPrintable\">" +
                                                    "                            <button  type=\"submit\" title=\"Delete\" class=\"btn btn-link btn-T \"><i class=\"fui-trash icon30\"></i></button>\n" +
                                                    "                               </td>"+
                                                    "                        </form>" +
                                                    "</tr>");
                                        }

                                    } catch (ClassNotFoundException e) {
                                        e.printStackTrace();
                                    } catch (SQLException e) {
                                        e.printStackTrace();
                                    }

                                %>
                                <%System.out.println("hjkldjkljksjfdjhjkhgjfskdhgfkhgfdhgghndvhf   58455644564545645645645645646     6");%>

                            </tbody>
                        </table>

                    <script>
                        $("#sTable").stupidtable();
                    </script>

                    <a class="btn btn-primary pull-left" href="index.jsp?page=addPILinks&cycle=<%=id%>&term=<%=Termid%>&programID=<%=request.getParameter("programID")%>">Add</a>
                    <a class="btn btn-primary pull-right" href="index.jsp?page=addTerm&cycle=<%=id%>&term=<%=Termid%>">Finish</a>

                    <!-- End of col -->
                </div>

                <!-- End of row -->
            </div>
        </div>
