    <%@ page import="ASDB.C_AS_Select" %>
<%@ page import="java.util.ArrayList" %>
<%@ page import="java.sql.SQLException" %>
<%@ page import="ASDB.AS_Select" %>
<%--
  Created by IntelliJ IDEA.
  User: Abdullah
  Date: 2/1/2016
  Time: 4:10 م
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<script src="/js/jquery-2.2.0.min.js" type="text/javascript"></script>
<script src="/js/bootbox.min.js" type="text/javascript"></script>
<script src="/js/flat-ui.min.js" type="text/javascript"></script>
<script src="/js/flat-ui-select.js" type="text/javascript"></script>


<%

    String id = "";
    if(request.getParameter("cycle") != null){
        id  = request.getParameter("cycle");
    }

%>

<%

    if(request.getParameter("status") != null){

        out.print("<script type=\"text/javascript\">\n" +
                "    $(window).load(function(){\n" +
                "       bootbox.alert(\""+request.getParameter("status")+"\")\n" +
                "    });\n" +
                "</script>");
    }

%>


<%
    AS_Select ASdbs = new AS_Select();
    ArrayList<String> uniData = null;
    try {
        uniData = ASdbs.selectUniversityData();
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    } catch (SQLException e) {
        e.printStackTrace();
    }
    if(uniData.get(2)!= null){
        out.println("<div id=\"print-note\" class=\" centerI\" > \n" +
                "                            <img width=\"135px\" class=\"\" " +
                "src=\""+uniData.get(2)+"\" alt=\""+uniData.get(0)+"\"></div>");
    }
%>
<h6 id="print-note">This ducument was generated by ABETAS for <%=uniData.get(1)%>, <%=uniData.get(0)%></h6>

        <div class="container">
            <div class="row">
                <div class="col-md-7 col-md-offset-2">
                    <nav>
                        <ol class="cd-breadcrumb triangle small">
                            <li class="current"><em>PI</em></li>
                            <li><em>Rubrics Names</em></li>
                            <li><em>Terms</em></li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- Here is row -->
            <div class="row">

            <h2 class="text-center">Add Program Performance Indicator</h2>

                <div class="col-md-8 col-md-offset-2">




                        <select class="form-control select select-primary select-block mbl" id="prgList" onchange="onPrgramChange(<%=id%>)" data-live-search="true">
                            <option data-tokens="select">Select program</option>

                                    <%
                                        C_AS_Select select = new C_AS_Select();
                                        ArrayList<Integer> pid = new ArrayList<Integer>();
                                        try {
                                            ArrayList<ArrayList<String>> rs = select.selectAllPrograms();
                                            ArrayList<String> rsRow;


                                            for (int i=0; i<rs.size();i++) {
                                                rsRow = rs.get(i);

                                                out.print("<option data-tokens=\""+rsRow.get(1)+"\" " );

                                                if(request.getParameter("programID")!=null && request.getParameter("programID").equals(rsRow.get(0))){
                                                    out.print(" selected=\"selected\" ");
                                                }

                                                        out.print(" value=\""+rsRow.get(0)+"\">"+rsRow.get(1)+"</option>");

                                            }
                                            if(request.getParameter("programID")!=null){
                                                out.print("<script>\n" +
                                                        "                                $(document).ready(function(){\n" +
                                                        "                                            onPrgramChange("+id+");\n" +
                                                        "                                        });\n" +
                                                        "                            </script>");
                                            }
                                        } catch (ClassNotFoundException e) {
                                            e.printStackTrace();
                                        } catch (SQLException e) {
                                            e.printStackTrace();
                                        }
                                    %>

                            <script>
                                function onPrgramChange(cid){
                                    var pl = document.getElementById("prgList");
                                    var pid = pl.options[pl.selectedIndex].value;
                                    if(pid == "Select program"){
                                        $("#pIList").hide();
                                    }else {
                                        show('page', false);
                                        show('loading', true);
                                        $.ajax({
                                            type: 'POST',
                                            data: {
                                                cid: cid,
                                                pid: pid
                                            },
                                            url: '/selectPI',
                                            success: function (result) {
                                                $('#pIList').html(result);
                                                $('#pIList').show();
                                                show('page', true);
                                                show('loading', false);

                                            }

                                        })
                                    }
                                }
                            </script>
                    </select>
                        </div>

                        <br>
                        <br>
                        <br>

                            <input name="cycle" value="<%=id%>" hidden/>




                <div id="pIList"></div>


                <a class="btn btn-primary btn-fill pull-right" href="index.jsp?page=rubricNames&cycle=<%=id%>">Next</a>
                    <a class="btn btn-default pull-right" href="index.jsp">Cancel</a>


                    <!-- End of col -->
                </div>
                <!-- End of row -->
            </div>

        </div>
